### ISSUE TITLE
Warning: Add either an 'id' or a 'scope' attribute to this <th> tag.

### ISSUE THREAD

**Issue by almerion** [DUT-Info-Montreuil/UniRide-SApp#86]
Associating <table> headers, i.e. `<th>` elements, with their `<td>` cells enables screen readers to announce the header prior to the data. This considerably increases the accessibility of tables to visually impaired users.

There are two ways of doing it:

- Adding a scope attribute to `<th>` headers.
- Adding an id attribute to `<th>` headers and a headers attribute to every `<td>` element.

It is recommended to add scope attributes to `<th> `headers whenever possible. Use `<th id="...">` and `<td headers="..."> `only when `<th scope="..."> `is not capable of associating cells to their headers. This happens for very complex tables which have headers splitting the data in multiple subtables. See [W3C WAI Web Accessibility Tutorials](https://www.w3.org/WAI/tutorials/tables/tips/) for more information.

Note that complex tables can often be split into multiple smaller tables, which improves the user experience.

This rule raises an issue when a `<th>` element has neither id nor scope attributes set.

Fichiers concerné:
- UniRide/.../document-verification-display/document-verification-display.component.html
- UniRide/.../components/manage-label-admin/manage-label-admin.component.html
- UniRide/.../app/admin/components/user-list/user-list.component.html
- UniRide/.../app/core/components/books-list/books-list.component.html
- UniRide/.../app/ranking/components/ranking/ranking.component.html
- UniRide/.../components/trip-passenger-list/trip-passenger-list.component.html
- UniRide/.../components/trip-proposed-list/trip-proposed-list.component.html
- UniRide/.../trip-search-result-list/trip-search-result-list.component.html

**Comment by Pawpawzz** [comment]
Done
